### ISSUE TITLE
Cannot upload Blink demo

### ISSUE THREAD

**Issue by baqwas** [SeeedDocument/Grove-AI-HAT-for-Edge-Computing#1]
Hello!

I cannot upload the standard Arduino **Blink** demo code to a **Grove AI HAT** from the Arduino IDE (v1.8.9). The code compiles (since no changes were made to the original source) but uploading gets frozen with the following message in the Output pane:

```
Sketch uses 88225 bytes (1%) of program storage space. Maximum is 8388608 bytes.
java.lang.NullPointerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingProgrammer(SerialUploader.java:295)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:90)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2070)
	at java.lang.Thread.run(Thread.java:748)

```

- The desktop client (for the Arduino IDE) is Ubuntu 19.04 (disco):

`
Linux BeUlta 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- The Additional Boards Manager URLs has the following entry in the drop-down list (for the AI HAT):

`https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json`

- The corresponding AI HAT library version number is 1.3.0.
- Board in in stand-alone mode with J4 set to ON position.

The board selected is _Seeed K210 Pi_ and baud rate and port are _1 Mbps_ and _/dev/ttyUSB1_ respectively. There is another port at USB2 and that choosing that port made no difference to the error output message.

Perhaps, as a newbie, I am doing something wrong. Any feedback would be sincerely appreciated.

Kind regards.

**Comment by Pillar1989** [comment]
I said in the documentation that if you are using Ubuntu, you need to follow the following packages
```
#ubuntu or debian
sudo apt update
sudo apt install python3 python3-pip
sudo pip3 install pyserial
```

**Comment by baqwas** [comment]
@Pillar1989 

All these packages are installed already in the desktop computer because these are used by other applications. What is the next step to resolve the issue?

**Comment by Pillar1989** [comment]
Can you provide all the compiling and uploading information of arduino?

**Comment by baqwas** [comment]
The Arduino version number is 1.8.9. It was downloaded from the official Arduino site, arduino.cc.

My English or my computer knowledge is not good. I don't know understand what "compiling and uploading information of arduino" means. The navigation steps used to reproduce the error repeatedly were:

- _Load source_: File -> Examples -> Basics -> Blink
- _Compiling: Sketch_ -> Verify/Compile
- _Uploading: Sketch_ -> Upload
